name: Test Silverstripe
on:
  push:
    paths-ignore:
      - README.md
      - LICENSE.md
jobs:
  test:
    name: phpunit
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: [7.2, 7.3, 7.4]
    services:
      database:
        image: mysql:8
        environment:
          MYSQL_ROOT_PASSWORD: silverstripe
          MYSQL_DATABASE: ss_default
          MYSQL_USER: silverstripe
          MYSQL_PASSWORD: silverstripe
          TZ: Europe/Zurich
        expose:
          - 3306
        command:
          - --default-authentication-plugin=mysql_native_password
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get Composer Cache Directory
        id: composer-data
        run: |
          echo "::set-output name=dir::$(composer config --global data-dir)"

      - name: Cache Composer Downloads
        uses: actions/cache@v1
        with:
          path: ${{ steps.composer-data.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ matrix.php }}-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer

      - name: Cache PHP dependencies
        uses: actions/cache@v1
        with:
          path: vendor
          key: ${{ runner.OS }}-build-composer-${{ matrix.php }}-${{ hashFiles('**/composer.lock') }}

      - name: Install Silverstripe
        container: composer
        env:
          COMPOSER_HOME: ${{ steps.composer-data.outputs.dir }}
        run: composer install --ignore-platform-reqs

      - name: Run tests
        container: brettt89/silverstripe-web:${TAG:-7.4}-apache
        env:
          SS_DEFAULT_ADMIN_USERNAME: admin
          SS_DEFAULT_ADMIN_PASSWORD: admin
          SS_DATABASE_SERVER: database
          SS_DATABASE_NAME: ss_default
          SS_DATABASE_USERNAME: root
          SS_DATABASE_PASSWORD: silverstripe
          SS_ENVIRONMENT_TYPE: dev
          TZ: Europe/Zurich
        run: vendor/bin/phpunit app/tests/
